project:
  type: website

website:
  title: Quarto website
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Report
        href: hello.qmd
      - text: Slides
        href: slides.qmd

format: html

execute:
  freeze: true
